### ISSUE TITLE
[$15] unable to delete a key/value on "Edit value" modal

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#40] opened 2018-12-06 16:30 UTC
### Reproduction Steps ###

1. open the app, expand all items on left side

2. click global-map, then select 2 rows, click Delete Key

3. try to delete any key/value on the Edit value modal, observe

### Expected Result ###

Delete button should be working.

### Actual Result ###

*See screenshot*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment] 2018-12-06 16:30
![map](https://user-images.githubusercontent.com/4590317/49597401-4fec0780-f9b7-11e8-9c55-d73124f0eb9e.jpg)

**Comment by ksmacleod99** [comment] 2018-12-21 19:23
duplicate of #33

**Closed by ksmacleod99** 2018-12-21 19:23 UTC
