### ISSUE TITLE
Save button is hidden, if string is too long

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#64] opened 2018-12-07 02:40 UTC
1. Deploy the App and Open
2. Select an item from the right view (String)
3. Add a long string value

**Actual:** Save button is hidden, if string is too long

**Expected:** Long string value should have scroll bars to scroll the content

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment] 2018-12-08 14:07
![image](https://user-images.githubusercontent.com/42398485/49686845-3e425700-fac0-11e8-940d-f1461e056b74.png)

**Comment by ksmacleod99** [comment] 2018-12-21 20:32
duplicate of #39

**Closed by ksmacleod99** 2018-12-21 20:32 UTC
Labels: P2
