### ISSUE TITLE
list cannot be scrolled down

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#50] opened 2018-12-06 16:58 UTC
### Reproduction Steps ###

1. open the app

2. expand all items on left

3. click on "global-ordered-list" of "default-local"

4. on the main table, try to scroll down to view more data

### Expected Result ###

Should be easy to scroll down.

### Actual Result ###

*See screenshot, very hard to scroll or even unable to see the scrollbar.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment] 2018-12-06 16:59
![scroll](https://user-images.githubusercontent.com/4590317/49599175-49f82580-f9bb-11e8-8cc2-6cf4434f265a.jpg)

**Comment by ksmacleod99** [comment] 2018-12-14 18:51
Duplicate of #28

**Closed by ksmacleod99** 2018-12-14 18:52 UTC
